config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    unlocks:       'users/unlocks',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  namespace :users do
    get 'contents/index'
    get 'contents/show'
    get 'contents/past_events_list'
  end
  
  namespace :events do
    get 'new_a'
    get 'new_b'
  end
  resources :events do
    member do
      post 'import'
      delete 'destroy_members_and_schedules'
      patch 'update_decision_of_schedule'
      patch 'update_chouseisan_check'
      get 'the_day'
      patch 'finish'
      get 'invitations/edit'
      patch 'invitations/update'
      post 'fees/create'
      patch 'fees/update'
    end
    patch 'members/update_all'
    resources :members do
      member do
        patch 'update_status'
      end
    end
    resources :shops do
      member do
        patch 'update_decision'
      end
    end
  end
  
  root 'static_pages#top'
end

app/controllers/users/contents_controller.rb
class Users::ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: %w[index]
  before_action :not_admin_user, only: %w[show]
  before_action :set_time, only: %w[show past_events_list]
  
  def index
#    debugger
    @users = User.paginate(page: params[:page], per_page: 10).search(params[:searchword]).where(admin: false).order(:id)
#    debugger
  end

  def show
    @events_soon = current_user.events.joins(:schedules).where(schedules: { decided: true}).where(schedules: { held_at: @past_time..@future_time }).order("schedules.held_at ASC")
    @events_after_a_few_days = current_user.events.joins(:schedules).where(schedules: { decided: true}).where(schedules: { held_at: @future_time...@last_max_time }).order("schedules.held_at ASC")
    @events_pending = current_user.events.where(event_status: "pending").order(:id)
#    debugger
  end
  
  def past_events_list
    @events_past = current_user.events.joins(:schedules).where(schedules: { decided: true}).where(schedules: { held_at: @first_min_time...@past_time }).order("schedules.held_at ASC")
  end
  
  private
  
    def set_time
      @first_min_time = Time.parse("1900/1/1 1") # Excelに見習って、登録は1900年～
      @past_time = Time.current - 60*60*12
      @future_time = (Time.current + 60*60*24*current_user.days_before).end_of_day
      @last_max_time = Time.current + 60*60*24*365*10 # 10年後まで登録可能。
    end
  
end

app/helpers/users/contents_helper.rb
module Users::ContentsHelper
end

app/views/users/contents/shows/_detail_events_list.html.erb
<table class="table table-bordered table-hover" id="table-event-detail">
  <% models.each_with_index do |event, counter| %>
    <% decided_schedule = event.schedules.find_by(decided: true) %>
    <% decided_shop = event.shops.find_by(decided: true) %>
    <% event_station = event.station.present? ? event.station : "" %>
    <% event_place = event.place.present? ? event.place : "" %>
    <% on_hold_numbers = decided_schedule.member_schedules.where(attendance_status: "on_hold").count if decided_schedule %>
    <tr>
      <td colspan="2">
        <div style="display:inline;">
          <p>
            <h2 style="display:inline;">
              <%= link_to "開始！", the_day_event_path(event), class: "btn btn-info btn-lg", target: :_blank %>
              <%= link_to event.event_name, event_path(event) %>
            </h2>
            <a class="btn btn-default pull-right" data-toggle="collapse" href="#collapse-event-index-<%= event.id %>-<%= counter %>">
              詳細
            </a>
          </p>
          
          <br>
          
          <% if decided_schedule.blank? %>
            <h4 style="display:inline;">日程：</h4>
            <%= render 'events/shows/pending_message', message: '日程調整中！' %>
            <%= render 'events/shows/pending_message', message: '人数調整中！' %>
          <% else %>
            <h3 style="display:inline;">
              <%= l(decided_schedule.held_at, format: :shortdate) %>
              <a class="<%= css_class_of_the_day(decided_schedule.held_at) %>">(<%= $days_of_the_week[decided_schedule.held_at.wday] %>)</a>
              <%= l(decided_schedule.held_at, format: :time) %>~
            </h3>
            <h3 style="display:inline;">
              ＜ <%= decided_schedule.attendance_numbers %>
              <%= "～#{decided_schedule.attendance_numbers + on_hold_numbers}" unless on_hold_numbers.zero? %>
              名 ＞
            </h3>
            <%= render 'events/shows/pending_message', message: '人数調整中！' unless on_hold_numbers.zero? %>
          <% end %>
          <% if event.chouseisan_check? %>
            <%= link_to "調整さんへ", event.chouseisan_url, class: "btn btn-success btn-sm", target: :_blank %>
            <button type="button" class="btn btn-info btn-sm clipboard-btn" data-clipboard-action="copy" data-clipboard-text="<%= event.chouseisan_url %>">URLコピー</button>
          <% else %>
            直接調整可
          <% end %>
          
          <br>
          <br>
          
          <% if decided_shop.blank? %>
            <h4 style="display:inline;">場所：</h4>
            <%= render 'events/shows/pending_message', message: '店調整中！' %>
            <%= form_with(model: event, local: true, class:"form-inline") do |f| %>
              <%= f.text_field :station, placeholder: "開催場所(駅名)を入力", class: "form-control" %>
              <h5 style="display:inline;">の</h5>
              <%= f.text_field :place, placeholder: "店の種類(居酒屋など)を入力", class: "form-control" %>
              <%= f.submit "変更", class: "btn btn-sm btn-primary btn-form" %>
              <%= link_to_web_search("駅名でお店をWeb検索", [event_station, event_place]) %>
            <% end %>
          <% else # 店が決まっている場合 %>
            <h3 style="display:inline;">
              <% if decided_shop.shop_url.blank? %>
                <%= decided_shop.shop_name %>
              <% else %>
                <%= link_to decided_shop.shop_name, decided_shop.shop_url, target: :_blank %>
              <% end %>
            </h3>
            <%= link_to_map("地図を表示", [decided_shop.shop_name, event_station]) %>
            <% if event_station.present? %>
              <h4 style="display:inline;"><%= "@#{event_station}" %></h4>
            <% end %>
          <% end %>
          
          <% if decided_shop.present? || event_station.present? %>
            <% if current_user.station.present? && event_station.present? %>
              <%= link_to_train_search("駅名で路線検索", current_user.station, event_station) %>
            <% else %>
              <%= link_to "路線検索", current_user.train_search_url, class: "btn btn-danger btn-sm", target: :_blank %>
              :「駅名で路線検索」を利用するには、
              <%= link_to "あなたの最寄り駅", edit_user_registration_path if current_user.station.blank? %>
              <%= "と" if current_user.station.blank? && event_station.blank? %>
              <%= link_to "開催地の最寄り駅", edit_event_path(event) if event_station.blank? %>
              を登録してください
            <% end %>
          <% end %>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        
        <div id="collapse-event-index-<%= event.id %>-<%= counter %>" class="collapse">
          <div class="well">
            <table class="table table-hover" id="table-event-detail-each">
              <tr>
                <td>
                  <h5 style="display:inline;">
                    <% if current_user.station.blank? || event_station.blank? %>
                      <%= form_with(model: event, local: true, class:"form-inline") do |f| %>
                        <h5 style="display:inline;">@</h5>
                        <%= f.text_field :station, placeholder: "開催場所(駅名)を入力", class: "form-control" %>
                        <h5 style="display:inline;">の</h5>
                        <%= f.text_field :place, placeholder: "店の種類(居酒屋など)を入力", class: "form-control" %>
                        <%= f.submit "変更", class: "btn btn-sm btn-primary btn-form" %>
                        <%= link_to_web_search("お店をWeb検索", [decided_shop.shop_name, event_station, event_place]) if decided_shop %>
                      <% end %>
                    <% else %>
                      <%= link_to_web_search("お店をWeb検索", [decided_shop.shop_name, event_station, event_place]) if decided_shop %>
                    <% end %>
                    <%= link_to_web_search("駅名でお店を再検索", [event_station, event_place]) if decided_shop.present? %>
                  </h5>
                </td>
                <td>
                  <%= link_to "削除", event_path(event), method: :delete, class: "btn btn-danger btn-sm pull-right",
                    data: {confirm: "「#{event.event_name}」を削除します。よろしいですか？"}
                  %>
                  <%= link_to "詳細", event_path(event), class: "btn btn-primary btn-sm pull-right" %>
                </td>
              </tr>
              <tr>
                <td colspan="1">
                  <h4 style="display:inline;"><%= show_text_of(event.chouseisan_note) %></h4>
                </td>
                <td colspan="1">
                  <h4 style="display:inline;"><%= show_text_of(decided_shop.remark) if decided_shop %></h4>
                </td>
              </tr>
            </table>
          </div>
        </div>
        
      </td>
    </tr>
  <% end %>
</table>

app/views/users/contents/shows/_events_list.html.erb
<table class="table table-bordered table-hover" id="table-event-detail">
  <% models.each_with_index do |event, counter| %>
    <% decided_schedule = event.schedules.find_by(decided: true) %>
    <% decided_shop = event.shops.find_by(decided: true) %>
    <% event_station = event.station#.present? ? event.station : "" %>
    <% event_place = event.place.present? ? event.place : "" %>
    <% on_hold_numbers = decided_schedule.member_schedules.where(attendance_status: "on_hold").count if decided_schedule %>
    <tr>
      <td colspan="2">
        <div style="display:inline;">
          <p>
            <h2 style="display:inline;">
              <%= link_to "開始！", the_day_event_path(event), class: "btn btn-info btn-lg", target: :_blank if decided_schedule && decided_schedule.held_at.between?(@past_time, @future_time) %>
              <%= link_to event.event_name, event_path(event) %>
            </h2>
            <h3 style="display:inline;">
              <%= "【#{event.event_status_i18n}】" %>
            </h3>
            <a class="btn btn-default pull-right" data-toggle="collapse" href="#collapse-event-index-<%= event.id %>-<%= counter %>">
              詳細
            </a>
          </p>
          
          <br>
          
          <% if decided_schedule.blank? %>
            <h4 style="display:inline;">日程：</h4>
            <%= render 'events/shows/pending_message', message: '日程調整中！' %>
            <%= render 'events/shows/pending_message', message: '人数調整中！' %>
          <% else %>
            <h3 style="display:inline;">
              <%= l(decided_schedule.held_at, format: :shortdate) %>
              <a class="<%= css_class_of_the_day(decided_schedule.held_at) %>">(<%= $days_of_the_week[decided_schedule.held_at.wday] %>)</a>
              <%= l(decided_schedule.held_at, format: :time) %>~
            </h3>
            <h3 style="display:inline;">
              ＜ <%= decided_schedule.attendance_numbers %>
              <%= "～#{decided_schedule.attendance_numbers + on_hold_numbers}" unless on_hold_numbers.zero? %>
              名 ＞
            </h3>
            <%= render 'events/shows/pending_message', message: '人数調整中！' unless on_hold_numbers.zero? %>
          <% end %>
          <% if event.chouseisan_check? %>
            <%= link_to "調整さんへ", event.chouseisan_url, class: "btn btn-success btn-sm", target: :_blank %>
            <button type="button" class="btn btn-info btn-sm clipboard-btn" data-clipboard-action="copy" data-clipboard-text="<%= event.chouseisan_url %>">URLコピー</button>
          <% else %>
            直接調整可
          <% end %>
          
          <br>
          <br>
          
          <% if decided_shop.blank? %>
            <h4 style="display:inline;">場所：</h4>
            <%= render 'events/shows/pending_message', message: '店調整中！' %>
            <%= form_with(model: event, local: true, class:"form-inline") do |f| %>
              <%= f.text_field :station, placeholder: "開催場所(駅名)を入力", class: "form-control" %>
              <h5 style="display:inline;">の</h5>
              <%= f.text_field :place, placeholder: "店の種類(居酒屋など)を入力", class: "form-control" %>
              <%= f.submit "変更", class: "btn btn-sm btn-primary btn-inline" %>
              <%= link_to_web_search(image_tag("/event/color_search.png", :size => "40x40"), [event_station, event_place]) %>
            <% end %>
          <% else # 店が決まっている場合 %>
            <h3 style="display:inline;">
              <% if decided_shop.shop_url.blank? %>
                <%= decided_shop.shop_name %>
              <% else %>
                <%= link_to decided_shop.shop_name, decided_shop.shop_url, target: :_blank %>
              <% end %>
            </h3>
            <%= link_to_web_search(image_tag("/event/color_search.png", :size => "40x40"), [decided_shop.shop_name, event_station, event_place]) %>
            <%= link_to_map(image_tag("/event/color_map.png", :size => "40x40"), [decided_shop.shop_name, event_station]) %>
            <% if event_station.present? %>
              <h4 style="display:inline;"><%= "@#{event_station}" %></h4>
            <% end %>
          <% end %>
          
          <% if decided_shop.present? || event_station.present? %>
            <% if current_user.station.present? && event_station.present? %>
              <%= link_to_train_search(image_tag("/event/color_train.png", :size => "40x40"), current_user.station, event_station) %>
            <% else %>
              <%= link_to image_tag("/event/simple_train.png", :size => "40x40"), current_user.train_search_url, class: "btn btn-sm", target: :_blank %>
              :「駅名で路線検索」を利用するには、
              <%= link_to "あなたの最寄り駅", edit_user_registration_path if current_user.station.blank? %>
              <%= "と" if current_user.station.blank? && event_station.blank? %>
              <%= link_to "開催地の最寄り駅", edit_event_path(event) if event_station.blank? %>
              を登録してください
            <% end %>
          <% end %>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        
        <div id="collapse-event-index-<%= event.id %>-<%= counter %>" class="collapse">
          <div class="well">
            <table class="table table-hover" id="table-event-detail-each">
              <tr>
                <td>
                  <h5 style="display:inline;">
                    <%= form_with(model: event, local: true, class:"form-inline") do |f| %>
                      <% if decided_shop.present? || current_user.station.present? && event_station.present? %>
                        <h5 style="display:inline;">@</h5>
                        <%= f.text_field :station, placeholder: "開催場所(駅名)を入力", class: "form-control" %>
                        <h5 style="display:inline;">の</h5>
                        <%= f.text_field :place, placeholder: "店の種類(居酒屋など)を入力", class: "form-control" %>
                        <%= f.submit "変更", class: "btn btn-sm btn-primary btn-inline" %>
                      <% end %>
                      <%= link_to_web_search(image_tag("/event/color_search.png", :size => "40x40"), [event_station, event_place]) if decided_shop.present? %>
                    <% end %>
                  </h5>
                </td>
                <td>
                  <h5 style="display:inline;">
                    <%= link_to "削除", event_path(event), method: :delete, class: "btn btn-danger btn-sm pull-right",
                      data: {confirm: "「#{event.event_name}」を削除します。よろしいですか？"}
                    %>
                    <%= link_to "詳細", event_path(event), class: "btn btn-primary btn-sm pull-right" %>
                  </h5>
                </td>
              </tr>
              <tr>
                <td colspan="1">
                  <h4 style="display:inline;"><%= show_text_of(event.chouseisan_note) %></h4>
                </td>
                <td colspan="1">
                  <h4 style="display:inline;"><%= show_text_of(decided_shop.remark) if decided_shop %></h4>
                </td>
              </tr>
            </table>
          </div>
        </div>
        
      </td>
    </tr>
  <% end %>
</table>