config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    unlocks:       'users/unlocks',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  namespace :users do
    get 'contents/index'
    get 'contents/show'
    get 'contents/past_events_list'
  end
  
  namespace :events do
    get 'new_a'
    get 'new_b'
  end
  resources :events do
    member do
      post 'import'
      delete 'destroy_members_and_schedules'
      patch 'update_decision_of_schedule'
      patch 'update_chouseisan_check'
      get 'the_day'
      patch 'finish'
      get 'invitations/edit'
      patch 'invitations/update'
      post 'fees/create'
      patch 'fees/update'
    end
    patch 'members/update_all'
    resources :members do
      member do
        patch 'update_status'
      end
    end
    resources :shops do
      member do
        patch 'update_decision'
      end
    end
  end
  
  root 'static_pages#top'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :shops, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :schedules, dependent: :destroy
  accepts_nested_attributes_for :schedules, allow_destroy: true
  enum event_status:[:pending, :schedule_decided, :shop_decided, :prepared, :being_held_now, :finished] # イベントの状態
  enum calculation_method_type:[:fixed, :dutch_treat, :slope] # 会計の計算方法
  
  VALID_URL_REGEX = /(\A\z)|(\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\z)/ix
#  VALID_CHOUSEISAN_URL_REGEX = /(\A\z)|(\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?+=[a-z0-9]\z)/ix
  validates :event_name, presence: true
  validates :chouseisan_url, presence: true, length: { maximum: 200 }, format: { with: VALID_URL_REGEX }, if: :create_with_chouseisan?
  validates :chouseisan_note, length: { maximum: 200 }
  validates :reference, length: { maximum: 200 }
#  validates :total_payment, presence: true
  
  # csvインポート処理
  def self.import(file, event)
    if file
      row_num = 0
      CSV.foreach(file.path, headers: false, encoding: 'Shift_JIS:UTF-8') do |row|
        row_num += 1
        case row_num
        when 1 # 1行目の処理（イベント名）
          event.update_attribute(:event_name, row[0])
        when 2 # 2行目の処理（イベント説明）
          event.update_attribute(:chouseisan_note, row[0])
        when 3 # 3行目の処理（表ヘッダー）
          for col in 1..(row.count-1) do
            if row[col]
              member = event.members.find_by(event_id: event.id, column_number: col) || event.members.new
              member.update_attributes(event_id: event.id, column_number: col, member_name: row[col])
            end
          end
        else # 4行目以降の処理（表の中身）
          unless row[0] == "コメント" # 4行目以降（最後の行は除く）の処理
            schedule = event.schedules.find_by(event_id: event.id, held_at: Time.zone.parse(row[0])) || event.schedules.new
            schedule.update_attributes(event_id: event.id, held_at: Time.zone.parse(row[0]))
            if row.count > 1
              for col in 1..(row.count-1) do
                if row[col]
                  member = event.members.find_by(column_number: col)
                  member_schedule = member.member_schedules.find_by(schedule_id: schedule.id) || member.member_schedules.new
                  case row[col]
                  when "○"
                    status = "to_attend"
                  when "△"
                    status = "on_hold"
                  when "×"
                    status = "to_be_absent"
                  end
                  member_schedule.update_attributes(member_id: member.id, schedule_id: schedule.id, attendance_status: status)
                end
              end
            end
            schedule.update_attribute(:attendance_numbers, schedule.member_schedules.where(attendance_status: "to_attend").count)
          else # 最後の行の処理
            if row.count > 1
              for col in 1..(row.count-1) do
                if row[col]
                  member = event.members.find_by(column_number: col)
                  member.update_attribute(:comment, row[col])
                end
              end
            end
          end
        end
      end
    end
  end


  private
    # 調整さんでnewするときのみバリデーション
    def create_with_chouseisan?
      !chouseisan_url.nil?
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, except: %w[new new_a new_b create index]
  before_action :set_only_new_event, only: %w[new new_a new_b]
  before_action :set_only_new_decided_schedule, only: %w[new new_b]
  before_action :set_number_of_members, except: %w[new new_a new_b create]
  #before_action :set_members, only: %w[the_day]
  before_action :correct_user, except: %w[new new_a new_b create index]
  before_action :correct_chouseisan_url, only: %w[show]
  
  def new
  end
  def new_a
  end
  def new_b
  end
  
  def create
    @event = current_user.events.new(event_schedule_params)
    if @event.chouseisan_url
      create_with_chouseisan
    else
      create_without_chouseisan
    end
  end
  
  def index
  end

  def show
    @total_fee = @decided_schedule.member_schedules.group(:attendance_status).sum(:fee) if @decided_schedule
    @the_day_check = false
    if @event.chouseisan_url && @event.chouseisan_check?
      if reg = /=/.match(@event.chouseisan_url)
        chouseisan_uid = reg.post_match
        @export_csv_url = 'https://chouseisan.com/schedule/List/createCsv?h=' + chouseisan_uid
      else
        flash[:danger] = "適切な調整さんURLを登録してください。"
        redirect_to edit_event_path(@event)
      end
    end
  end
  
  def the_day
#      debugger
    first_time_check = @event.event_status
    if @decided_schedule.present? && @event.update_attribute(:event_status, "being_held_now")
      @fee_numbers = @decided_schedule.member_schedules.where(attendance_status: "to_attend", payment_status: "not_yet").count
      @fee_much_numbers = @decided_schedule.member_schedules.where(attendance_status: "to_attend", payment_status: "not_yet_much").count
      @total_fee = @decided_schedule.member_schedules.group(:attendance_status).sum(:fee)
      @total_fee_payed = @decided_schedule.member_schedules.where(attendance_status: "to_attend").group(:payment_status).sum(:fee)
      @total_payment_from_now_on = (@event.total_payment || 0) - (@total_fee_payed["already_payed"] || 0)
      @the_day_check = true
      flash[:success] = @event.event_name + 'を開催しました。（当日モードです。）' unless first_time_check == "being_held_now"
    else
      flash[:danger] = 'なぜか当日モードになりませんでした。管理者にお問い合わせください。'
      redirect_to_home_page_url
    end
  end
  
  def finish
    if @event.update_attribute(:event_status, "finished")
      flash[:success] = @event.event_name + 'が無事終了しました。お疲れさまでした。'
      redirect_to_home_page_url
    else
      flash[:danger] = 'なぜか当日モードになりませんでした。管理者にお問い合わせください。'
      redirect_to the_day_event_path(@event)
    end
  end
  
  def edit
  end
  
  def update
    if @event.update_attributes(event_schedule_params)
      flash[:success] = @event.event_name + 'を更新しました。'
      redirect_to @event
    else
      render action: :edit
    end
  end
  
  def update_decision_of_schedule
    if params[:schedule_id] && @decided_schedule.blank?
      if @event.schedules.find(params[:schedule_id]).update_attribute(:decided, true) && @event.update_attribute(:event_status, "schedule_decided")
        flash[:success] = @event.event_name + 'の日程を' + l(@event.schedules.find(params[:schedule_id]).held_at, format: :short)+ 'に決定しました！'
      else
        flash[:danger] = 'なぜか日程の決定に失敗しました。管理者にお問い合わせください。'
      end
    else
      if @decided_schedule.update_attribute(:decided, false) && @event.update_attribute(:event_status, "pending")
        flash[:success] = @event.event_name + 'の日程を再考することにしました。'
      else
        flash[:danger] = 'なぜか日程のリセットに失敗しました。管理者にお問い合わせください。'
      end
    end
    redirect_to @event
  end
  
  def update_chouseisan_check
    if @decided_schedule.present? && @event.chouseisan_check?
      if @event.update_attribute(:chouseisan_check, false)
        flash[:success] = @event.event_name + 'を直接編集できます。（今後、調整さんの変更は反映されません。）'
      else
        flash[:danger] = 'なぜか切替に失敗しました。管理者にお問い合わせください。'
      end
    else
      if @event.update_attribute(:chouseisan_check, true)
        flash[:success] = @event.event_name + 'を「調整さん」で更新できます。'
      else
        flash[:danger] = 'なぜか切替に失敗しました。管理者にお問い合わせください。'
      end
    end
    if params[:new_or_edit_chouseisan_url] == "true"
      flash[:success] = 'STEP１～３にしたがって「' + @event.event_name + '」用の調整さんURLを作成し、登録してください。'
      redirect_to edit_event_path(@event)
    else
      redirect_to @event
    end
  end
  
  def destroy
    @event.destroy
    flash[:success] = 'イベント「' + @event.event_name + '」を削除しました。'
    redirect_to users_contents_show_url
  end
  
  def destroy_members_and_schedules
    if Member.where(event_id: @event.id).destroy_all && Schedule.where(event_id: @event.id).destroy_all
      flash[:success] = '参加者と日程を全て削除しました。'
      redirect_to event_url(@event)
    else
      flash[:danger] = 'なぜか参加者と日程の削除に失敗しました。'
      render action: :show
    end
  end
  
  # csvインポート（引数に@eventが必要）
  def import
    # fileはtmpに自動で一時保存される
    Event.import(params[:file], @event)
    if params[:file]
      flash[:success] = "#{:file}をインポートしました。"
    else
      flash[:danger] = "ファイルを選択してください。"
    end
    redirect_to event_url(@event)
  end
  
  private

    # 調整さんで新規イベント作成
    def create_with_chouseisan
      @event.event_name = "（未更新）"
      if @event.save
        flash[:success] = '調整さんURLを登録しました。早速更新してみましょう！'
        redirect_to event_url(@event)
      else
        render :new_a
      end
    end
    
    # 調整さんなしで直接新規イベント作成
    def create_without_chouseisan
      @event.chouseisan_check = false
      @event.event_status = "schedule_decided"
      @event.schedules.first.decided = true
      if @event.save
        @decided_schedule = @event.schedules.first
        @decided_schedule.attendance_numbers.times do |number|
          @member = @event.members.new(member_params)
          @member.member_name = "member#{number + 1}"
          if @member.save
            decided_status = @member.member_schedules.new(schedule_id: @decided_schedule.id, attendance_status: "to_attend")
            unless decided_status.save
              flash[:danger] = 'decided_scheduleモデルの保存時に予期せぬエラーが発生しました。管理者にお問い合わせください。'
              redirect_to event_url(@event) and return
            end
          else
            flash[:danger] = 'システムエラーによりmemberの自動生成に失敗しました。管理者にお問い合わせください。'
            redirect_to event_url(@event) and return
          end
        end
        flash[:danger] = '過去の日付に設定されています。' if @decided_schedule.held_at < Time.current
        flash[:success] = '次は「まとめて編集」で参加者の名前を登録しましょう！'
        redirect_to event_url(@event)
          
      else
        set_only_new_decided_schedule
        render :new_b
      end
    end
    
    
    # beforeフィルター
  
    # 対象のイベントを取得。
    def set_event
#      debugger
      set_id = params[:event_id].blank? ? params[:id] : params[:event_id]
      if Event.exists?(set_id)
        @event = Event.find(set_id)
        if @decided_schedule = @event.schedules.find_by(event_id: @event.id, decided: true)
          @decided_members = @event.members.joins(:member_schedules).where(member_schedules: { attendance_status: "to_attend", schedule_id: @decided_schedule.id }).order(:id).paginate(page: params[:page], per_page: 10)
          @on_hold_members = @event.members.joins(:member_schedules).where(member_schedules: { attendance_status: "on_hold", schedule_id: @decided_schedule.id }).order(:id).paginate(page: params[:page], per_page: 10)
          @to_be_absent_members = @event.members.joins(:member_schedules).where(member_schedules: { attendance_status: "to_be_absent", schedule_id: @decided_schedule.id }).order(:id).paginate(page: params[:page], per_page: 10)
        else
          @event.update_attribute(:event_status, "pending")
        end
        @schedules = @decided_schedule.present? ? @event.schedules.where(event_id: @event.id, decided: true).order(:held_at) : @event.schedules.all
        @decided_shop = @event.shops.find_by(event_id: @event.id, decided: true)
        @shops = @event.shops.all.paginate(page: params[:page], per_page: 10).order(:id)
      else
        flash[:danger] = 'set_event:error; id=' + set_id + 'のデータは存在しません。'
        redirect_to_home_page_url
      end
    end
    
    # new event
    def set_only_new_event
      @event = current_user.events.new
    end
    
    # new decided_schedule
    def set_only_new_decided_schedule
      @decided_schedule = @event.schedules.new(held_at: Time.current.change(hour: 19, min:0, sec: 0))
    end
    
    # 参加人数を取得。
    def set_number_of_members
      if @decided_schedule && @decided_statuses
        @decided_schedule.update_attribute(:attendance_numbers, @decided_statuses.count)
      end
    end
    
    # アクセスしたユーザーが現在ログインしているユーザー本人か確認。
    def correct_user
      unless current_user == User.find(@event.user_id)
        flash[:danger] = "別アカウントの情報にアクセスしようとしています。URLを確認してください。"
        redirect_to_home_page_url
      end
    end
    
    # chouseisan_checkがtrueであるにも関わらず、urlが登録されていない場合は、編集画面へ飛ばす
    def correct_chouseisan_url
      if @event.chouseisan_check? && @event.chouseisan_url.blank?
        flash[:danger] = "適切な調整さんURLを登録してください。"
        redirect_to edit_event_path(@event)
      end
    end
    
    
    # strong parameter
    
    # Event#new
    def event_params
      params.require(:event).permit(:event_name,
                                    :event_status,
                                    :chouseisan_note,
                                    :chouseisan_url,
                                    :chouseisan_check,
                                    :place,
                                    :station,
                                    :indication_price,
                                    :deadline,
                                    :reserved_at,
                                    :reserved_by,
                                    :reserved_number_of_members,
                                    :reference)
    end
    
    # Schedule#new
    def schedule_params
      params.require(:event).permit(schedules: [:held_at,

app/helpers/events_helper.rb
module EventsHelper
  # 土日は色をつけるclass
  def css_class_of_the_day(day)
    case $days_of_the_week[day.wday]
    when "土"
      "text-primary"
    when "日"
      "text-danger"
    else
      "text-muted"
    end
  end
  
end

app/views/events/_chouseisan_form.html.erb
<%= render 'users/shared/error_messages', resource: model %>
<% if explanation_need == true %>
  <%= link_to image_tag("/chouseisan/chouseisan_icon.png", :size => "120x30"), "https://chouseisan.com/", target: :_blank %>で日程調整<br>
  STEP１. <%= link_to "「調整さん」(https://chouseisan.com/)へアクセス", "https://chouseisan.com/", target: :_blank %><br>
  STEP２. 「調整さん」で出欠表をつくり、URLをコピー<br>
  STEP３. 「調整さん」のURLを登録。
<% end %>
<%= form_with(model: model, local: true, class:"form-inline") do |f| %>
  <%= f.label :chouseisan_url, class: "label-form" %>
  <%= f.text_field :chouseisan_url, autofocus: true, placeholder: "ここにURLをコピペ", class: "form-control" %>
  <%= f.submit "登録", class: "btn btn-sm btn-success btn-inline" %>
<% end %>

app/views/events/_edit_place.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_with(model: @event, local: true, class:"form-inline") do |f| %>
      <%= f.text_field :station, placeholder: "開催場所(駅名)を入力", class: "form-control" %>
      <h5 style="display:inline;">の</h5>
      <%= f.text_field :place, placeholder: "店の種類(居酒屋など)を入力", class: "form-control" %>
      <%= f.submit "変更", class: "btn btn-sm btn-primary btn-inline" %>
      <button type="button" class="btn btn-info btn-sm clipboard-btn" data-clipboard-action="copy" data-clipboard-text="<%= @event.station %>">駅名コピー</button>
      <%= link_to_web_search(image_tag("/event/color_search.png", :size => "40x40"), [@event.station, @event.place]) %>
      <% if current_user.station.present? && @event.station.present? %>
        <%= link_to_train_search(image_tag("/event/color_train.png", :size => "40x40"), current_user.station, @event.station) %>
      <% else %>
        <%= link_to image_tag("/event/simple_train.png", :size => "35x35"), current_user.train_search_url, class: "btn btn-sm", target: :_blank %>
            :「駅名で路線検索」を利用するには、
            <%= link_to "あなたの最寄り駅", edit_user_registration_path if current_user.station.blank? %>
            <%= "と" if current_user.station.blank? && @event.station.blank? %>
            <%= link_to "開催地の最寄り駅", edit_event_path(@event) if @event.station.blank? %>
            を登録してください
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/_event_form.html.erb
<%= form_with(model: model, local: true) do |f| %>
  <%= render 'users/shared/error_messages', resource: model %>
  <%= render 'users/shared/error_messages', resource: schedule_model %>
  
  <%= f.label :event_name, class: "label-#{yield(:class_text)}" %>(※必須)
  <%= f.text_field :event_name, autofocus: true, placeholder: "イベント名を入力", class: "form-control" %>
  
  <%= f.label :station, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :station, placeholder: "開催予定の最寄り駅を入力", class: "form-control" %>

  <%= f.label :place, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :place, placeholder: "予約する店の種類を入力（検索や案内文に反映されます）", class: "form-control" %>

  <%= f.label :indication_price, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :indication_price, placeholder: "会費を入力（実費精算の場合は空欄）", class: "form-control" %>
  
  <%= f.fields_for :schedules, schedule_model do |schedule| %>
  
    <% if schedule_model.new_record? %>
      <%= schedule.label :held_at, class: "label-#{yield(:class_text)}" %>(※必須)
      <%= schedule.datetime_local_field :held_at, class: "form-control" %>
    
      <%= schedule.label :attendance_numbers, class: "label-#{yield(:class_text)}" %>(※必須)
      <%= schedule.number_field :attendance_numbers, min:2, max:150, value: 4, class: "form-control" %>
      
    <% else %>
      <%= schedule.label :held_at, class: "label-#{yield(:class_text)}" %>(※必須)
      <%= schedule.datetime_local_field :held_at, class: "form-control" %>
      
    <% end %>
    
  <% end %>
  
  
  <%= f.label :chouseisan_note, class: "label-#{yield(:class_text)}" %>
  <%= f.text_area :chouseisan_note, placeholder: "開催趣旨や補足説明はこちら", class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/events/edit.html.erb
<% provide(:title, 'Edit-Event') %>
<% provide(:class_text, 'event--edit') %>
<% provide(:button_text, 'イベント編集') %>
<h1>イベントの編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if @event.chouseisan_check? || @event.errors.messages[:chouseisan_url].present? %>
      <%= render 'chouseisan_form', model: @event, explanation_need: true %>
    <% else %>
      <%= render 'event_form', model: @event, schedule_model: @decided_schedule %>
    <% end %>
  </div>
</div>
<% if @event.chouseisan_check? && @event.chouseisan_url.nil? %>
  <%= link_to 'URLを登録せずに戻る（やっぱり直接編集する）', update_chouseisan_check_event_path(@event), method: :patch, class: "pull-right" %><br>
<% else %>
  <%= link_to "「#{@event.event_name}」のページへ戻る", event_path(@event), class: "pull-right" %>
<% end %>

app/views/events/index.html.erb
<% provide(:title, "Members of #{@event.event_name}") %>
<h2 style="text-align:center">【メンバー編集】</h2>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      
      <div class="all_members_edit">
        <h3 style="display:inline;">＜<%= status_title(@members.first.member_schedules.first.attendance_status) %>＞</h3>
        <h3 style="display:inline;"><%= @members.count %>名</h3>
      </div>
      <% unless @members.blank? %>
        <%= render 'members/edit_index', models: @members, first_number: @first_number %>
      <% end %>

    </div>
  </div>
</div>

app/views/events/new.js.erb
$("#new-event").html("<%= escape_javascript(render 'new') %>");
$("#new-event").modal("show");

app/views/events/new_a.html.erb
<% provide(:title, 'New-Event') %>
<% provide(:class_text, 'event--new') %>
<% provide(:button_text, 'イベント作成') %>
<h1>新規イベントの作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'chouseisan_form', model: @event, explanation_need: true %>
    <%= link_to "日程が調整済の場合はこちら", events_new_b_path %>
  </div>
</div>

app/views/events/new_b.html.erb
<% provide(:title, 'New-Event') %>
<% provide(:class_text, 'event--new') %>
<% provide(:button_text, 'イベント作成') %>
<h1>新規イベントの作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'event_form', model: @event, schedule_model: @decided_schedule %>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.event_name) %>
<%= link_to "現在このイベントは開催中です。当日モードはこちら", the_day_event_path(@event), class:"pull-right" if @event.event_status == "being_held_now" %><br>
<%= link_to image_tag("/event/koushin.png", :size => "30x30"), event_path(@event), class:"pull-right" %>
<h4><%= "進捗：#{@event.event_status_i18n}" %></h4>

<div class="text-center">
  <h1><%= @event.event_name %></h1>
  <h4 style="display:inline;"><%= show_text_of(@event.chouseisan_note) %></h4>
  <h5 style="display:inline;">
    <% if @event.chouseisan_check? %>
      <%= link_to "編集（調整さん）", @event.chouseisan_url, target: :_blank %>
    <% else %>
      <%= link_to image_tag("/event/edit.png", :size => "20x20"), edit_event_path(@event) %>
    <% end %>
  </h5>
</div>

<br>

<div>
  <h3 style="display:inline;">＜日程＞</h3>
  <% if @decided_schedule.blank? %>
    <%= render 'events/shows/pending_message', message: '調整中！' %>
  <% else %>
    <%= render 'events/shows/decided_schedule', model: @decided_schedule %>
  <% end %>
</div>
<div><%= render 'events/shows/chouseisan_table' if @event.chouseisan_check? %></div>

<br>

<div>
  <% if @decided_schedule.blank? %>
    <h3 style="display:inline;">＜参加者＞</h3>
    <%= render 'events/shows/pending_message', message: '未定！' %>
  <% elsif @event.chouseisan_check? %>
    <%= render 'events/shows/members_list', the_day_check: false %>
    <%= render 'events/shows/to_direct_edit' %>
  <% else %>
    <%= render 'events/shows/members_list', the_day_check: false %>
    <%= render 'events/shows/to_chouseisan_edit' %>
  <% end %>
</div>

<br>

<div>
  <h3 style="display:inline;">＜会費＞
    <%= @event.indication_price.present? ? "#{@event.indication_price}円" : "実費" %>
  </h3>
  <h5 style="display:inline;">
    <%= link_to image_tag("/event/edit.png", :size => "20x20"), edit_event_path(@event) unless @event.chouseisan_check? %>
  </h5>
</div>

<br>
<br>

<% event_station = @event.station#.present? ? @event.station : "" %>
<% event_place = @event.place#.present? ? @event.place : "" %>
<div>
  <h3 style="display:inline;">＜場所＞</h3>
  <% if @decided_shop.blank? %>
    <%= render 'events/shows/pending_message', message: '調整中！' %>
  <% else %>
    <%= render 'events/shows/decided_shop', shop: @decided_shop %>
  <% end %>
</div>
<div>
  <h4 style="display:inline;">
    <%= render 'events/edit_place' %>
  </h4>
</div>
<div>
  <% if @decided_shop.blank? %>
    <%= render 'events/shows/shop_index', models: @shops %>
  <% else %>
    <%= render 'events/shows/shop_show', model: @decided_shop %>
  <% end %>
</div>



<script type="text/javascript">
    var clipboard = new Clipboard('.btn');
    clipboard.on('success', function(e) {
      //成功時の処理
      console.info('Trigger:', e.trigger);
    });
    clipboard.on('error', function(e) {
      //失敗時の処理
      console.error('Trigger:', e.trigger);
    });
</script>

<!--モーダルウインドウ表示-->
<div id="member-index" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="shop-edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/events/the_day.html.erb
<% provide(:title, @event.event_name) %>
<p class="text-right">現在「当日モード」です。「調整モード」は<%= link_to "こちら", event_path(@event), class:"pull-right" %></p>
<%= link_to image_tag("/event/koushin.png", :size => "30x30"), the_day_event_path(@event), class:"pull-right" %>

<div class="text-center">
  <h1>
    <%= render 'events/shows/pending_message', message: '【開催中】' %>
    <h1 style="display:inline;"><%= @event.event_name %></h1>
  </h1>
  <br>
  <h4 style="display:inline;"><%= show_text_of(@event.chouseisan_note) %></h4>
  <h5 style="display:inline;">
    <%= link_to image_tag("/event/edit.png", :size => "20x20"), edit_event_path(@event) %>
  </h5>
</div>

<br>

<div>
  <h3 style="display:inline;">＜日程＞</h3>
  <%= render 'events/shows/decided_schedule', model: @decided_schedule, the_day_check: true %>
</div>
<div><%= link_to "調整さんテーブルを見る", event_path(@event), class:"pull-right" if @event.chouseisan_check? %></div>

<br>

<div>
  <%= render 'events/shows/members_list', the_day_check: true %>
</div>

<br>

<div>
  <h3 style="display:inline;">＜会計＞</h3>
  <h4 style="display:inline;"><%= render 'fees/edit' %></h4>
</div>

<br>
<br>

<% event_station = @event.station.present? ? @event.station : "" %>
<% event_place = @event.place.present? ? @event.place : "" %>
<div>
  <h3 style="display:inline;">＜場所＞</h3>
  <% if @decided_shop.blank? %>
    <%= render 'events/shows/pending_message', message: '調整中！' %>
  <% else %>
    <%= render 'events/shows/decided_shop', shop: @decided_shop %>
  <% end %>
</div>
<div>
  <h4 style="display:inline;">
    <%= render 'events/edit_place' %>
  </h4>
</div>
<div>
  <% if @decided_shop.blank? %>
    <%= render 'events/shows/shop_index', models: @shops %>
  <% else %>
    <%= render 'events/shows/shop_show', model: @decided_shop %>
  <% end %>
</div>

<%= link_to "このイベントを完了する！", finish_event_path(@event), method: :patch, class: "btn btn-danger btn-block" %>


<!--モーダルウインドウ表示-->
<div id="member-index" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="shop-edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>