config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    unlocks:       'users/unlocks',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  namespace :users do
    get 'contents/index'
    get 'contents/show'
    get 'contents/past_events_list'
  end
  
  namespace :events do
    get 'new_a'
    get 'new_b'
  end
  resources :events do
    member do
      post 'import'
      delete 'destroy_members_and_schedules'
      patch 'update_decision_of_schedule'
      patch 'update_chouseisan_check'
      get 'the_day'
      patch 'finish'
      get 'invitations/edit'
      patch 'invitations/update'
      post 'fees/create'
      patch 'fees/update'
    end
    patch 'members/update_all'
    resources :members do
      member do
        patch 'update_status'
      end
    end
    resources :shops do
      member do
        patch 'update_decision'
      end
    end
  end
  
  root 'static_pages#top'
end

app/controllers/fees_controller.rb
class FeesController < EventsController
  before_action :authenticate_user!
  before_action :set_event#, except: %w[new new_a new_b create index]
  before_action :correct_user#, except: %w[new new_a new_b create index]
  
  def edit
  end
  
  def create
    if event_fee_params[:total_payment].present?
      if @event.update_attributes(event_fee_params)
        @fee_numbers = @decided_schedule.member_schedules.where(attendance_status: "to_attend", payment_status: "not_yet").count
        @fee_much_numbers = @decided_schedule.member_schedules.where(attendance_status: "to_attend", payment_status: "not_yet_much").count
        @total_fee = @decided_schedule.member_schedules.group(:attendance_status).sum(:fee)
        @total_fee_payed = @decided_schedule.member_schedules.where(attendance_status: "to_attend").group(:payment_status).sum(:fee)
        @total_payment_from_now_on = @event.total_payment - (@total_fee_payed["already_payed"] || 0)
        @the_day_check = true
        if @fee_numbers > 0 || @fee_much_numbers > 0
          case params[:commit]
            when "会費を指定"
              @event.update_attribute(:calculation_method_type, "fixed")
              @fee = @event.indication_price || 0
              @fee_much = @event.indication_price || 0
              flash.now[:danger] = '「会費を指定」するには、予想会費を入力してください。' if @event.indication_price.blank?
            when "割り勘計算"
              @event.update_attribute(:calculation_method_type, "dutch_treat")
              calculate_slope(1)
            when "傾斜で計算"
              @event.update_attribute(:calculation_method_type, "slope")
              calculate_slope(@event.rate_of_fee_slope || 1)
              flash.now[:danger] = '「傾斜で計算」するには、傾斜率を入力してください。' if @event.rate_of_fee_slope.blank?
            else
              flash.now[:danger] = "計算に失敗しました。管理者にお問い合わせください。"
              render action: :edit
          end
        end
        @sum = @fee*@fee_numbers + @fee_much*@fee_much_numbers
        flash.now[:success] = @event.event_name + 'の会計計算結果が出ました。採用する場合は「計算結果を反映」ボタンを押してください。'
        render action: :the_day
      else
        render action: :edit
      end
    else
      flash[:danger] = '支払総額を入力してください。'
      redirect_to the_day_event_path(@event)
    end
  end
  
  def update
    if params[:fee].present? && params[:fee_much].present?
      @fee_members = @decided_schedule.member_schedules.where(attendance_status: "to_attend", payment_status: "not_yet")
      @fee_members.each do |m_s|
        m_s.update_attribute(:fee, params[:fee])
      end
      @fee_much_members = @decided_schedule.member_schedules.where(attendance_status: "to_attend", payment_status: "not_yet_much")
      @fee_much_members.each do |m_s|
        m_s.update_attribute(:fee, params[:fee_much])
      end
      flash[:success] = @event.event_name + 'の会計計算結果を反映しました。'
      redirect_to the_day_event_path(@event)
    else
      flash.now[:danger] = "反映に失敗しました。管理者にお問い合わせください。"
      render action: :the_day
    end
  end
    
  
  private
  
    def calculate_slope(rate)
      unit = @event.fee_unit || 1
      fee = @total_payment_from_now_on / (rate*@fee_much_numbers + @fee_numbers)
      fee_much = rate*fee
      sum_loose = fee.ceil_to(unit)*@fee_numbers + fee_much.floor_to(unit)*@fee_much_numbers
      sum_steep = fee.floor_to(unit)*@fee_numbers + fee_much.ceil_to(unit)*@fee_much_numbers
      if (@total_payment_from_now_on.between?(sum_steep, sum_loose) || sum_loose.between?(@total_payment_from_now_on, sum_steep)) && (fee.ceil_to(unit) <= fee_much.floor_to(unit))
        @fee = fee.ceil_to(unit)
        @fee_much = fee_much.floor_to(unit)
      elsif @total_payment_from_now_on.between?(sum_loose, sum_steep) || sum_steep.between?(@total_payment_from_now_on, sum_loose)
        @fee = fee.floor_to(unit)
        @fee_much = fee_much.ceil_to(unit)
      else
        @fee = fee.ceil_to(unit)
        @fee_much = fee_much.ceil_to(unit)
      end
    end
  
    # strong parameter
    
    # invitation#update
    def event_fee_params
      params.require(:event).permit(:total_payment, 
                                    :fee_unit,
                                    :rate_of_fee_slope,
                                    :indication_price)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/views/fees/_edit.html.erb
<% provide(:class_text, 'event--edit') %>
<%= form_with(model: @event, url: fees_create_event_path(@event), local: true, method: :post, class:"form-inline") do |f| %>
  <%#= hidden_field_tag :event_id, @event %>
  <table class="table table-hover table-condensed" id="table-fees">
    <thead>
      <tr>
        <td colspan="1"><%= "① 4つの欄を入力" if @fee.blank? %></td>
        <td colspan="1"><%= "② 計算" if @fee.blank? %></td>
        <td colspan="1"><%= "※必須" %></td>
        <td colspan="1"><%= "③ 計算結果(#{@event.calculation_method_type_i18n})を確認" if @fee.present? %></td>
        <td>現状</td>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td class="text-changed">
            <%= f.label :indication_price, class: "label-#{yield(:class_text)}" %>
            <%= f.number_field :indication_price, min:0, max:1e6, step: "#{@event.fee_unit}", placeholder: "会費を指定", class: "form-control" %>円
          </td>
          <td><%= f.submit "会費を指定", class: "btn btn-sm btn-primary btn-form" %></td>
          <td>
            <%= f.label :total_payment, class: "label-#{yield(:class_text)}" %>
            <%= f.number_field :total_payment, min:0, max:1e6, placeholder: "入力必須", class: "form-control" %>円
          </td>
          <td>支払総額 - 集金済：<%= @total_payment_from_now_on || "（未定）" %>円</td>
          <td>集金済：<%= @total_fee_payed["already_payed"] || 0 %>円</td>
        </tr>
        <tr>
          <td>
            <%= f.label :fee_unit, class: "label-#{yield(:class_text)}" %>
            <%= f.number_field :fee_unit, min:1, max:10000, placeholder: "1", class: "form-control" %>円単位
          </td>
          <td><%= f.submit "割り勘計算", class: "btn btn-sm btn-primary btn-form" %></td>
          <td>通常の方（<%= @fee_numbers if @fee_numbers.present? %>人）：<%= @fee if @fee.present? %>円</td>
          <td><%= "要集金額：#{@sum}円" if @sum.present? %></td>
          <td>集金予定総額：<%= @total_fee["to_attend"] || 0 %>円</td>
        </tr>
        <tr>
          <td>
            <%= f.label :rate_of_fee_slope, class: "label-#{yield(:class_text)}" %>：約
            <%= f.number_field :rate_of_fee_slope, min:0.1, max:100, step:0.1, placeholder: "1", class: "form-control" %>倍
          </td>
          <td><%= f.submit "傾斜で計算", class: "btn btn-sm btn-primary btn-form" %></td>
          <td>多めの方（<%= @fee_much_numbers if @fee_much_numbers.present? %>人）：<%= @fee_much if @fee_much.present? %>円</td>
          <td>
            <% if @total_payment_from_now_on.present? && @sum.present? %>
              余り：<%= @sum - @total_payment_from_now_on %>円
              <% if @sum >= @total_payment_from_now_on %>
                <%= render 'events/shows/pending_message', message: 'OK!' %>
              <% else %>
                <%= render 'events/shows/pending_message', message: '再計算を推奨' %>
              <% end %>
            <% end %>
          </td>
          <td>残り：<%= (@total_fee_payed["not_yet"] || 0) + (@total_fee_payed["not_yet_much"] || 0) %>円未回収</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td colspan="2"><%= link_to "④ 計算結果を反映", fees_update_event_path(@event, fee: @fee, fee_much: @fee_much), method: :patch, class:"btn btn-primary btn-block" if @fee.present? %></td>
          <td colspan="1"><%= link_to "反映しない（現状キープ）", the_day_event_path(@event), class:"btn btn-primary btn-block" if @fee.present? %></td>
        </tr>
    </tbody>
  </table>
<% end %>