config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    unlocks:       'users/unlocks',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  namespace :users do
    get 'contents/index'
    get 'contents/show'
    get 'contents/past_events_list'
  end
  
  namespace :events do
    get 'new_a'
    get 'new_b'
  end
  resources :events do
    member do
      post 'import'
      delete 'destroy_members_and_schedules'
      patch 'update_decision_of_schedule'
      patch 'update_chouseisan_check'
      get 'the_day'
      patch 'finish'
      get 'invitations/edit'
      patch 'invitations/update'
      post 'fees/create'
      patch 'fees/update'
    end
    patch 'members/update_all'
    resources :members do
      member do
        patch 'update_status'
      end
    end
    resources :shops do
      member do
        patch 'update_decision'
      end
    end
  end
  
  root 'static_pages#top'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :shops, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :schedules, dependent: :destroy
  accepts_nested_attributes_for :schedules, allow_destroy: true
  enum event_status:[:pending, :schedule_decided, :shop_decided, :prepared, :being_held_now, :finished] # イベントの状態
  enum calculation_method_type:[:fixed, :dutch_treat, :slope] # 会計の計算方法
  
  VALID_URL_REGEX = /(\A\z)|(\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\z)/ix
#  VALID_CHOUSEISAN_URL_REGEX = /(\A\z)|(\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?+=[a-z0-9]\z)/ix
  validates :event_name, presence: true
  validates :chouseisan_url, presence: true, length: { maximum: 200 }, format: { with: VALID_URL_REGEX }, if: :create_with_chouseisan?
  validates :chouseisan_note, length: { maximum: 200 }
  validates :reference, length: { maximum: 200 }
#  validates :total_payment, presence: true
  
  # csvインポート処理
  def self.import(file, event)
    if file
      row_num = 0
      CSV.foreach(file.path, headers: false, encoding: 'Shift_JIS:UTF-8') do |row|
        row_num += 1
        case row_num
        when 1 # 1行目の処理（イベント名）
          event.update_attribute(:event_name, row[0])
        when 2 # 2行目の処理（イベント説明）
          event.update_attribute(:chouseisan_note, row[0])
        when 3 # 3行目の処理（表ヘッダー）
          for col in 1..(row.count-1) do
            if row[col]
              member = event.members.find_by(event_id: event.id, column_number: col) || event.members.new
              member.update_attributes(event_id: event.id, column_number: col, member_name: row[col])
            end
          end
        else # 4行目以降の処理（表の中身）
          unless row[0] == "コメント" # 4行目以降（最後の行は除く）の処理
            schedule = event.schedules.find_by(event_id: event.id, held_at: Time.zone.parse(row[0])) || event.schedules.new
            schedule.update_attributes(event_id: event.id, held_at: Time.zone.parse(row[0]))
            if row.count > 1
              for col in 1..(row.count-1) do
                if row[col]
                  member = event.members.find_by(column_number: col)
                  member_schedule = member.member_schedules.find_by(schedule_id: schedule.id) || member.member_schedules.new
                  case row[col]
                  when "○"
                    status = "to_attend"
                  when "△"
                    status = "on_hold"
                  when "×"
                    status = "to_be_absent"
                  end
                  member_schedule.update_attributes(member_id: member.id, schedule_id: schedule.id, attendance_status: status)
                end
              end
            end
            schedule.update_attribute(:attendance_numbers, schedule.member_schedules.where(attendance_status: "to_attend").count)
          else # 最後の行の処理
            if row.count > 1
              for col in 1..(row.count-1) do
                if row[col]
                  member = event.members.find_by(column_number: col)
                  member.update_attribute(:comment, row[col])
                end
              end
            end
          end
        end
      end
    end
  end


  private
    # 調整さんでnewするときのみバリデーション
    def create_with_chouseisan?
      !chouseisan_url.nil?
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, except: %w[new new_a new_b create index]
  before_action :set_only_new_event, only: %w[new new_a new_b]
  before_action :set_only_new_decided_schedule, only: %w[new new_b]
  before_action :set_number_of_members, except: %w[new new_a new_b create]
  #before_action :set_members, only: %w[the_day]
  before_action :correct_user, except: %w[new new_a new_b create index]
  before_action :correct_chouseisan_url, only: %w[show]
  
  def new
  end
  def new_a
  end
  def new_b
  end
  
  def create
    @event = current_user.events.new(event_schedule_params)
    if @event.chouseisan_url
      create_with_chouseisan
    else
      create_without_chouseisan
    end
  end
  
  def index
  end

  def show
    @total_fee = @decided_schedule.member_schedules.group(:attendance_status).sum(:fee) if @decided_schedule
    @the_day_check = false
    if @event.chouseisan_url && @event.chouseisan_check?
      if reg = /=/.match(@event.chouseisan_url)
        chouseisan_uid = reg.post_match
        @export_csv_url = 'https://chouseisan.com/schedule/List/createCsv?h=' + chouseisan_uid
      else
        flash[:danger] = "適切な調整さんURLを登録してください。"
        redirect_to edit_event_path(@event)
      end
    end
  end
  
  def the_day
#      debugger
    first_time_check = @event.event_status
    if @decided_schedule.present? && @event.update_attribute(:event_status, "being_held_now")
      @fee_numbers = @decided_schedule.member_schedules.where(attendance_status: "to_attend", payment_status: "not_yet").count
      @fee_much_numbers = @decided_schedule.member_schedules.where(attendance_status: "to_attend", payment_status: "not_yet_much").count
      @total_fee = @decided_schedule.member_schedules.group(:attendance_status).sum(:fee)
      @total_fee_payed = @decided_schedule.member_schedules.where(attendance_status: "to_attend").group(:payment_status).sum(:fee)
      @total_payment_from_now_on = (@event.total_payment || 0) - (@total_fee_payed["already_payed"] || 0)
      @the_day_check = true
      flash[:success] = @event.event_name + 'を開催しました。（当日モードです。）' unless first_time_check == "being_held_now"
    else
      flash[:danger] = 'なぜか当日モードになりませんでした。管理者にお問い合わせください。'
      redirect_to_home_page_url
    end
  end
  
  def finish
    if @event.update_attribute(:event_status, "finished")
      flash[:success] = @event.event_name + 'が無事終了しました。お疲れさまでした。'
      redirect_to_home_page_url
    else
      flash[:danger] = 'なぜか当日モードになりませんでした。管理者にお問い合わせください。'
      redirect_to the_day_event_path(@event)
    end
  end
  
  def edit
  end
  
  def update
    if @event.update_attributes(event_schedule_params)
      flash[:success] = @event.event_name + 'を更新しました。'
      redirect_to @event
    else
      render action: :edit
    end
  end
  
  def update_decision_of_schedule
    if params[:schedule_id] && @decided_schedule.blank?
      if @event.schedules.find(params[:schedule_id]).update_attribute(:decided, true) && @event.update_attribute(:event_status, "schedule_decided")
        flash[:success] = @event.event_name + 'の日程を' + l(@event.schedules.find(params[:schedule_id]).held_at, format: :short)+ 'に決定しました！'
      else
        flash[:danger] = 'なぜか日程の決定に失敗しました。管理者にお問い合わせください。'
      end
    else
      if @decided_schedule.update_attribute(:decided, false) && @event.update_attribute(:event_status, "pending")
        flash[:success] = @event.event_name + 'の日程を再考することにしました。'
      else
        flash[:danger] = 'なぜか日程のリセットに失敗しました。管理者にお問い合わせください。'
      end
    end
    redirect_to @event
  end
  
  def update_chouseisan_check
    if @decided_schedule.present? && @event.chouseisan_check?
      if @event.update_attribute(:chouseisan_check, false)
        flash[:success] = @event.event_name + 'を直接編集できます。（今後、調整さんの変更は反映されません。）'
      else
        flash[:danger] = 'なぜか切替に失敗しました。管理者にお問い合わせください。'
      end
    else
      if @event.update_attribute(:chouseisan_check, true)
        flash[:success] = @event.event_name + 'を「調整さん」で更新できます。'
      else
        flash[:danger] = 'なぜか切替に失敗しました。管理者にお問い合わせください。'
      end
    end
    if params[:new_or_edit_chouseisan_url] == "true"
      flash[:success] = 'STEP１～３にしたがって「' + @event.event_name + '」用の調整さんURLを作成し、登録してください。'
      redirect_to edit_event_path(@event)
    else
      redirect_to @event
    end
  end
  
  def destroy
    @event.destroy
    flash[:success] = 'イベント「' + @event.event_name + '」を削除しました。'
    redirect_to users_contents_show_url
  end
  
  def destroy_members_and_schedules
    if Member.where(event_id: @event.id).destroy_all && Schedule.where(event_id: @event.id).destroy_all
      flash[:success] = '参加者と日程を全て削除しました。'
      redirect_to event_url(@event)
    else
      flash[:danger] = 'なぜか参加者と日程の削除に失敗しました。'
      render action: :show
    end
  end
  
  # csvインポート（引数に@eventが必要）
  def import
    # fileはtmpに自動で一時保存される
    Event.import(params[:file], @event)
    if params[:file]
      flash[:success] = "#{:file}をインポートしました。"
    else
      flash[:danger] = "ファイルを選択してください。"
    end
    redirect_to event_url(@event)
  end
  
  private

    # 調整さんで新規イベント作成
    def create_with_chouseisan
      @event.event_name = "（未更新）"
      if @event.save
        flash[:success] = '調整さんURLを登録しました。早速更新してみましょう！'
        redirect_to event_url(@event)
      else
        render :new_a
      end
    end
    
    # 調整さんなしで直接新規イベント作成
    def create_without_chouseisan
      @event.chouseisan_check = false
      @event.event_status = "schedule_decided"
      @event.schedules.first.decided = true
      if @event.save
        @decided_schedule = @event.schedules.first
        @decided_schedule.attendance_numbers.times do |number|
          @member = @event.members.new(member_params)
          @member.member_name = "member#{number + 1}"
          if @member.save
            decided_status = @member.member_schedules.new(schedule_id: @decided_schedule.id, attendance_status: "to_attend")
            unless decided_status.save
              flash[:danger] = 'decided_scheduleモデルの保存時に予期せぬエラーが発生しました。管理者にお問い合わせください。'
              redirect_to event_url(@event) and return
            end
          else
            flash[:danger] = 'システムエラーによりmemberの自動生成に失敗しました。管理者にお問い合わせください。'
            redirect_to event_url(@event) and return
          end
        end
        flash[:danger] = '過去の日付に設定されています。' if @decided_schedule.held_at < Time.current
        flash[:success] = '次は「まとめて編集」で参加者の名前を登録しましょう！'
        redirect_to event_url(@event)
          
      else
        set_only_new_decided_schedule
        render :new_b
      end
    end
    
    
    # beforeフィルター
  
    # 対象のイベントを取得。
    def set_event
#      debugger
      set_id = params[:event_id].blank? ? params[:id] : params[:event_id]
      if Event.exists?(set_id)
        @event = Event.find(set_id)
        if @decided_schedule = @event.schedules.find_by(event_id: @event.id, decided: true)
          @decided_members = @event.members.joins(:member_schedules).where(member_schedules: { attendance_status: "to_attend", schedule_id: @decided_schedule.id }).order(:id).paginate(page: params[:page], per_page: 10)
          @on_hold_members = @event.members.joins(:member_schedules).where(member_schedules: { attendance_status: "on_hold", schedule_id: @decided_schedule.id }).order(:id).paginate(page: params[:page], per_page: 10)
          @to_be_absent_members = @event.members.joins(:member_schedules).where(member_schedules: { attendance_status: "to_be_absent", schedule_id: @decided_schedule.id }).order(:id).paginate(page: params[:page], per_page: 10)
        else
          @event.update_attribute(:event_status, "pending")
        end
        @schedules = @decided_schedule.present? ? @event.schedules.where(event_id: @event.id, decided: true).order(:held_at) : @event.schedules.all
        @decided_shop = @event.shops.find_by(event_id: @event.id, decided: true)
        @shops = @event.shops.all.paginate(page: params[:page], per_page: 10).order(:id)
      else
        flash[:danger] = 'set_event:error; id=' + set_id + 'のデータは存在しません。'
        redirect_to_home_page_url
      end
    end
    
    # new event
    def set_only_new_event
      @event = current_user.events.new
    end
    
    # new decided_schedule
    def set_only_new_decided_schedule
      @decided_schedule = @event.schedules.new(held_at: Time.current.change(hour: 19, min:0, sec: 0))
    end
    
    # 参加人数を取得。
    def set_number_of_members
      if @decided_schedule && @decided_statuses
        @decided_schedule.update_attribute(:attendance_numbers, @decided_statuses.count)
      end
    end
    
    # アクセスしたユーザーが現在ログインしているユーザー本人か確認。
    def correct_user
      unless current_user == User.find(@event.user_id)
        flash[:danger] = "別アカウントの情報にアクセスしようとしています。URLを確認してください。"
        redirect_to_home_page_url
      end
    end
    
    # chouseisan_checkがtrueであるにも関わらず、urlが登録されていない場合は、編集画面へ飛ばす
    def correct_chouseisan_url
      if @event.chouseisan_check? && @event.chouseisan_url.blank?
        flash[:danger] = "適切な調整さんURLを登録してください。"
        redirect_to edit_event_path(@event)
      end
    end
    
    
    # strong parameter
    
    # Event#new
    def event_params
      params.require(:event).permit(:event_name,
                                    :event_status,
                                    :chouseisan_note,
                                    :chouseisan_url,
                                    :chouseisan_check,
                                    :place,
                                    :station,
                                    :indication_price,
                                    :deadline,
                                    :reserved_at,
                                    :reserved_by,
                                    :reserved_number_of_members,
                                    :reference)
    end
    
    # Schedule#new
    def schedule_params
      params.require(:event).permit(schedules: [:held_at,

app/helpers/events_helper.rb
module EventsHelper
  # 土日は色をつけるclass
  def css_class_of_the_day(day)
    case $days_of_the_week[day.wday]
    when "土"
      "text-primary"
    when "日"
      "text-danger"
    else
      "text-muted"
    end
  end
  
end

app/views/events/shows/_chouseisan_url.html.erb
<p>
  調整さんURL:
  <%= link_to @event.chouseisan_url, @event.chouseisan_url, target: :_blank %>
  <%= link_to "URLへ飛ぶ", @event.chouseisan_url, class: "btn btn-default btn-sm", target: :_blank %>
  <button type="button" class="btn btn-info btn-sm clipboard-btn" data-clipboard-action="copy" data-clipboard-text="<%= @event.chouseisan_url %>">URLコピー</button>
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseURLedit">
    URL編集
  </a>
  <%= link_to "調整さんURLの案内文を作成", invitations_edit_event_path(@event), class: "btn btn-warning btn-sm pull-right", target: :_blank %>
</p>
<div id="collapseURLedit" class="collapse">
  <div class="well">
    <%= render 'chouseisan_form', model: @event, explanation_need: false %>
  </div>
</div>

app/views/events/shows/_members_list_for_each_status.html.erb
<% status_key = models.first.member_schedules.find_by(schedule_id: @decided_schedule.id).attendance_status %>
<% colspan_number = @event.chouseisan_url.present? ? 6 : 5 %>
<% number_key = first_number %>
<% first_number += (params[:page].to_i - 1)*10 if params[:page] %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= will_paginate models %>
    <table class="table table-hover" id="table-members">
      <thead>
        <tr>
          <td colspan="1"><%= models.first.member_schedules.find_by(schedule_id: @decided_schedule.id).attendance_status_i18n %></td>
          <td colspan="1">名前</td>
          <% if @event.chouseisan_url.present? %>
            <td colspan="1">本人コメント</td>
          <% end %>
          <td colspan="1">備考</td>
          <td colspan="1">会費計：<%= @total_fee["#{status_key}"] if @total_fee.present? %></td>
          <td colspan="1">
            <% if @event.chouseisan_check? %>
              <%= link_to "編集(調整さん)", @event.chouseisan_url, target: :_blank %>
            <% else %>
              <%= link_to "まとめて編集", event_members_path(@event, status_key: status_key, number_key: number_key), remote: true %>
            <% end %>
          </td>
        </tr>
      </thead>
      <tbody>
        <div>
          <% models.each_with_index do |member, counter| %>
            <% m_s = member.member_schedules.find_by(schedule_id: @decided_schedule.id) %>
            <tr>
              <td><%= counter + first_number %></td>
              <td><%= member.member_name %></td>
              <% if @event.chouseisan_url.present? %>
                <td><%= show_text_of(member.comment) %></td>
              <% end %>
              <td><%= show_text_of(member.remark) %></td>
              <td><%= m_s.fee %>円</td>
              <td>
                <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#collapse-edit-member-<%= counter + first_number %>">
              	  編集
              	</a>
              </td>
            </tr>
            <tr>
              <% #debugger %>
              <td colspan = "<%= colspan_number %>" >
                <div id="collapse-edit-member-<%= counter + first_number %>" class="collapse">
                	<div class="well">
                	  <%= form_with(url: event_member_path(@event, member), model: member, local: true, class:"form-inline") do |f| %>
                      <% #debugger %>
                      <% unless @event.chouseisan_check? %>
                        <%= link_to "出席に変更", update_status_event_member_path(@event, member, attendance_id: m_s.id, key: 2), method: :patch, class: "btn btn-info btn-sm" unless m_s.attendance_status == "to_attend" %>
                        <%= link_to "保留に変更", update_status_event_member_path(@event, member, attendance_id: m_s.id, key: 1), method: :patch, class: "btn btn-warning btn-sm" unless m_s.attendance_status == "on_hold" %>
                        <%= link_to "欠席に変更", update_status_event_member_path(@event, member, attendance_id: m_s.id, key: 0), method: :patch, class: "btn btn-danger btn-sm" unless m_s.attendance_status == "to_be_absent" %>
                        <%= link_to "削除", 
                          event_member_path(@event, member), 
                          method: :delete, 
                          data: {confirm: "「#{member.member_name}」を削除します。よろしいですか？"}, 
                          class: "btn btn-danger btn-xs"
                        %>
                        <br>
                        <%= f.label :member_name, class: "label-form" %>(※空欄不可)
                        <%= f.text_field :member_name, class: "form-control" %>
                        <br>
                      <% end %>
                      <%= f.label :remark, class: "label-form" %>
                      <%= f.text_field :remark, autofocus: true, class: "form-control" %>
                      <%= f.submit "変更", class: "btn btn-sm btn-primary btn-form" %>
                    <% end %>
        
                	</div>
                </div>
              </td>
            </tr>
          <% end %>
          
          <% unless @event.chouseisan_check? || models.first.member_schedules.first.attendance_status == "to_be_absent" %>
            <tr>
              <td></td>
              <td>
                <a class="btn btn-primary btn-xs" data-toggle="collapse" href="#collapse-new-member-<%= models.first.member_schedules.first.attendance_status %>">
              	  追加
              	</a>
              </td>
              <% if @event.chouseisan_url.present? %>
                <td></td>
              <% end %>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td colspan = "<%= colspan_number %>" >
                <div id="collapse-new-member-<%= models.first.member_schedules.first.attendance_status %>" class="collapse">
                	<div class="well">
                	  <% new_member = @event.members.new %>
                	  <%= form_with(model:[@event, new_member], local: true, class:"form-inline") do |f| %>
                      <%= render 'users/shared/error_messages', resource: new_member %>
                      <%= hidden_field_tag :status_key, models.first.member_schedules.first.attendance_status %>
                      <%= f.label :member_name, class: "label-form" %>(※空欄不可)
                      <%= f.text_field :member_name, autofocus: true, value: "member#{@event.members.all.count + 1}", class: "form-control" %>
                      <br>
                      <%= f.label :remark, class: "label-form" %>
                      <%= f.text_field :remark, class: "form-control" %>
                      <%= f.submit "追加", class: "btn btn-sm btn-primary btn-form" %>
                    <% end %>
                	</div>
                </div>
              </td>
            </tr>
          <% end %>
          
        </div>
      </tbody>
    </table>
    <%= will_paginate models %>
  </div>
</div>

app/views/events/shows/_members_table.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= will_paginate models %>
    <table class="table table-hover" id="table-members">
      <thead>
        <tr>
          <td colspan="1"><%= models.first.attendance_status_i18n %></td>
          <td colspan="1">名前</td>
          <td colspan="1">本人コメント</td>
          <td colspan="1">備考</td>
          <td colspan="1"><%= link_to "まとめて編集", "#" %></td>
        </tr>
      </thead>
      <tbody>
        <div>
          <% first_number = (@decided_schedule.attendance_numbers - models.count).zero? ? 1 : (@decided_schedule.attendance_numbers + 1) %>
          <% models.each_with_index do |m_s, counter| %>
            <% @member = @event.members.find(m_s.member_id) %>
            <tr>
              <td><%= counter + first_number %></td>
              <td><%= @member.member_name %></td>
              <td><%= @member.comment %></td>
              <td><%= @member.remark %></td>
              <td>
                <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#collapse-edit-member-<%= counter + first_number %>">
              	  編集
              	</a>
              </td>
            </tr>
            <tr>
              <td colspan="5">
                <div id="collapse-edit-member-<%= counter + first_number %>" class="collapse">
                	<div class="well">
                	  <%= form_with(url: event_member_path(@event, @member), model: @member, local: true, class:"form-inline") do |f| %>
                      <%= render 'users/shared/error_messages', resource: @member %>
                      <% #debugger %>
                      <% unless @event.chouseisan_check? %>
                        <% if m_s.attendance_status == "to_attend" %>
                          <%= link_to "保留に変更", update_status_event_member_path(@event, @member, attendance_id: m_s.id, key: 1), method: :patch, class: "btn btn-warning btn-sm" %>
                        <% else %>
                          <%= link_to "出席に変更", update_status_event_member_path(@event, @member, attendance_id: m_s.id, key: 2), method: :patch, class: "btn btn-info btn-sm" %>
                        <% end %>
                        <%= link_to "欠席に変更", update_status_event_member_path(@event, @member, attendance_id: m_s.id, key: 0), method: :patch, class: "btn btn-danger btn-sm" %>
                        <%= link_to "削除", 
                          event_member_path(@event, @member), 
                          method: :delete, 
                          data: {confirm: "「#{@member.member_name}」を削除します。よろしいですか？"}, 
                          class: "btn btn-danger btn-xs"
                        %>
                        <br>
                        <%= f.label :member_name, class: "label-form" %>
                        <%= f.text_field :member_name, class: "form-control" %>
                        <br>
                      <% end %>
                      <%= f.label :remark, class: "label-form" %>
                      <%= f.text_field :remark, class: "form-control" %>
                      <%= f.submit "変更", class: "btn btn-sm btn-primary btn-form" %>
                    <% end %>
                    
        
                	</div>
                </div>
              </td>
            </tr>
          <% end %>
          
          <tr>
            <td></td>
            <td>
              <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#collapse-new-member-<%= models.first.attendance_status %>">
            	  追加
            	</a>
            </td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td colspan="5">
              <div id="collapse-new-member-<%= models.first.attendance_status %>" class="collapse">
              	<div class="well">
              	  <% @member = @event.members.new %>
              	  <%= form_with(model:[@event, @member], local: true, class:"form-inline") do |f| %>
                    <%= render 'users/shared/error_messages', resource: @member %>
                    <%= hidden_field_tag :status_key, models.first.attendance_status %>
                    <% #debugger %>
                    <%= f.label :member_name, class: "label-form" %>
                    <%= f.text_field :member_name, class: "form-control" %>
                    <br>
                    <%= f.label :remark, class: "label-form" %>
                    <%= f.text_field :remark, class: "form-control" %>
                    <%= f.submit "追加", class: "btn btn-sm btn-primary btn-form" %>
                  <% end %>
              	</div>
              </div>
            </td>
          </tr>
          
        </div>
      </tbody>
    </table>
    <%= will_paginate models %>
  </div>
</div>

app/views/events/shows/_pending_message.html.erb
<h2 class="pending_message"><%= message %></h2>

app/views/events/shows/_shop_show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table table-hover" id="table-shops">
      <tbody>
        <tr>
          <td>
          </td>
          <td>
            <% if @shop.present? && @shop.id.to_s == params[:id] %>
              <%= render 'users/shared/error_messages', resource: @shop %>
              <%= link_to "OK", event_path(@event), class: "btn btn-default btn-xs pull-right" if @shop.errors.present? %>
            <% end %>
            <div>
              <h4 style="display:inline;">＜店名＞</h4>
              <h3 style="display:inline;"><%= model.shop_name %></h3>
              <%= link_to image_tag("/event/edit.png", :size => "20x20"), edit_event_shop_path(@event, model), remote: true %>
            </div>
            <p>
              <h4 style="display:inline;">＜URL＞</h4>
              <%= link_to model.shop_url, model.shop_url, target: :_blank %>
              <%= link_to "WEBサイト表示", model.shop_url, class: "btn btn-primary btn-sm", target: :_blank if model.shop_url %>
              <button type="button" class="btn btn-info btn-sm clipboard-btn" data-clipboard-action="copy" data-clipboard-text="<%= model.shop_url %>">URLコピー</button>
              <a class="btn btn-default" data-toggle="collapse" href="#collapse-decided-shop">
                編集
              </a>
              <%= link_to_web_search(image_tag("/event/color_search.png", :size => "40x40"), [model.shop_name, @event.station]) %>
            </p>
            <% if model.shop_address.present? %>
              <div>
                <h4 style="display:inline;">＜住所＞<%= model.shop_address %></h4>
                <%= link_to_map(image_tag("/event/color_map.png", :size => "40x40"), [model.shop_address]) %>
              </div>
            <% end %>
            <div>
              <%= form_with(model:[@event, model], local: true, class:"form-inline") do |f| %>
                <%= f.label :remark, class: "label-form" %>
                <%= f.text_area :remark, placeholder: "ここにメモが書けます", size: "50x2", class: "form-control" %>
                <%= f.submit "メモを保存", class: "btn btn-sm btn-primary btn-form" %>
              <% end %>
            </div>
            <div id="collapse-decided-shop" class="collapse">
              <div class="well">
                <%= render 'shops/shop_form_full', model: model %>
              </div>
            </div>

          </td>
        </tr>

      </tbody>
    </table>
  </div>
</div>